languageCode = "zh-cn"
languageName = "简体中文"
weight = 2
title = "m4rsquake"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  # logo = "img/profile_photo.jpg"
  description = "这是简体中文页面。"

[params.author]
  name = "m4rsquake"
  image = "img/profile_photo.jpg"
  headline = "总结中深刻，输出中精进"
  bio = "蒟蒻一枚"
  links = [
    { github = "https://github.com/m4rsquake/PageSource" },
  ]