languageCode = "en"
languageName = "English"
weight = 1
title = "m4rsquake's homepage"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/profile_photo.jpg"
  description = "This is English page."

[params.author]
  name = "m4rsquake"
  email = "m4rsquake@outlook.com"
  image = "img/profile_photo.jpg"
  headline = "Observe things principles and understand their strategies."
  bio = "Studying nuclear technology and applications."
  links = [
    { github = "https://github.com/m4rsquake" },
  ]