# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "congo"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
showComments = false # 显示评论

replyByEmail = false

mainSections = ["pages"]
# robots = ""

disableImageOptimization = false
disableTextInHeader = false
# backgroundImageWidth = 1200

defaultBackgroundImage = "/img/background.svg"
defaultFeaturedImage = "/img/featured.svg"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

[header]
  layout = "basic" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[footer]
  showMenu = true
  showCopyright = true # 显示版权信息
  showThemeAttribution = false # 显示主题归属信息
  showAppearanceSwitcher = true # 显示主题切换按钮
  showScrollToTop = true # 显示回到顶部按钮

[homepage]
  layout = "page" # valid options: page, profile, hero, card, background, custom
  # homepageImage = "/img/iceland.jpg" # used in: hero, and card
  showRecent = true # 显示最近文章列表
  showRecentItems = 6
  showMoreLink = false # 在主页底部添加"显示更多"按钮
  showMoreLinkDest = "article" # "显示更多"按钮指向的位置
  cardView = true # 将列表显示为卡片容器
  cardViewScreenWidth = false # 增强列表中卡片的宽度，使其可以占据可用的全部宽度
  layoutBackgroundBlur = true # only used when layout equals background

[article]
  showDate = false
  showViews = true
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = true
  showAuthor = false
  showAuthorBottom = false
  showHero = false
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  showBreadcrumbs = true # 展示面包屑导航
  showDraftLabel = true
  showEdit = false
  editURL = "https://github.com/m4rsquake/PageSource/tree/main/content"
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = false
  showPagination = false
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 6
  showTaxonomies = true 
  showAuthorsBadges = true 
  showWordCount = true
  sharingLinks = [ "twitter", "reddit", "whatsapp", "telegram", "facebook", "email"]
  showZenMode = true

[list]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showSummary = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  showCards = true
  orderByWeight = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  cardView = false

[term]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  
[firebase]
  apiKey = "AIzaSyDGyYk2bcopSwJ0a0SynLDYSR13D6oMhSA"
  authDomain = "m4rsqauke-smainpage.firebaseapp.com"
  projectId = "m4rsqauke-smainpage"
  storageBucket = "m4rsqauke-smainpage.firebasestorage.app"
  messagingSenderId = "43792055088"
  appId = "1:43792055088:web:ff6c6bc9a03b5c7caa66f5"
  measurementId = "G-YGF31E13C5"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[umamiAnalytics]
  websiteid = "f931da9f-2444-4d77-8d1c-f57db5d1841e"
  # domain = "llama.yoursite.com"
  # dataDomains = "yoursite.com,yoursite2.com"
  # scriptName = ""
  # enableTrackEvent = false

[selineAnalytics]
  # token = "XXXXXX"
  # enableTrackEvent = false

[buymeacoffee]
  identifier = "m4rsquake"
  globalWidget = true
  globalWidgetMessage = ""
  globalWidgetColor = "#FFDD00"
  globalWidgetPosition = "Right"

[verification]
  google = "s9nH6v3Fme8M9ZFkKh5ATK1zr95FvcmFurvsKfyGSIs"
  bing = "DF72F5D705C5B3523D8B2F45FE5146D2"
  # pinterest = ""
  yandex = "ca80a7afa4c6356e"

[rssnext]
  # feedId = ""
  # userId = ""